services:
  - type: web
    name: thashreef-marine-uae-demo
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start -- -H 0.0.0.0 -p $PORT
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_INCLUDE
        value: dev
      - key: AUTH_SECRET
        generateValue: true
