"use client";

import { useTransition, type ReactElement } from "react";
import type { AdminOrder } from "@/domain/demo-store/demo-store-repository";
import { updateOrderStatusAction } from "@/features/orders/order.actions";
import { formatAedFromCents } from "@/shared/utils/currency";

export function AdminOrdersPage({ orders }: { orders: AdminOrder[] }): ReactElement {
  return <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-bold text-[#102846]">Customer order requests</h2><p className="mt-1 text-sm text-slate-500">Accept an order to begin confirmation, or reject it when it cannot be fulfilled.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs tracking-wide text-slate-500 uppercase"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Delivery</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Total</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{orders.map((order) => <tr key={order.id}><td className="px-5 py-4"><p className="font-bold text-slate-800">#{order.id}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("en-AE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.orderDate))}</p></td><td className="px-5 py-4"><p className="font-bold text-slate-800">{order.customerName}</p><p className="text-xs text-slate-500">{order.customerEmail}</p></td><td className="px-5 py-4 text-slate-600">{order.shippingZone}</td><td className="px-5 py-4 text-slate-600">Cash on Delivery</td><td className="px-5 py-4 font-bold text-slate-800">{formatAedFromCents(order.totalAedCents)}</td><td className="px-5 py-4"><Status status={order.status} /></td><td className="px-5 py-4">{order.status === "new" ? <OrderActions id={order.id} /> : <span className="text-xs font-semibold text-slate-500">Final decision saved</span>}</td></tr>)}{orders.length === 0 ? <tr><td className="px-5 py-12 text-center text-slate-500" colSpan={7}>Placed customer orders will appear here.</td></tr> : null}</tbody></table></div></section>;
}

function OrderActions({ id }: { id: number }): ReactElement { const [pending, startTransition] = useTransition(); const submit = (status: "accepted" | "rejected") => startTransition(() => { const data = new FormData(); data.set("id", String(id)); data.set("status", status); void updateOrderStatusAction(data); }); return <div className="flex gap-2"><button className="min-h-10 rounded-xl bg-emerald-600 px-3 text-xs font-bold text-white disabled:bg-slate-300" disabled={pending} onClick={() => submit("accepted")} type="button">Accept</button><button className="min-h-10 rounded-xl border border-rose-200 px-3 text-xs font-bold text-rose-700 disabled:text-slate-400" disabled={pending} onClick={() => submit("rejected")} type="button">Reject</button></div>; }
function Status({ status }: { status: string }): ReactElement { const style = status === "accepted" ? "bg-emerald-50 text-emerald-700" : status === "rejected" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${style}`}>{status}</span>; }
