import Link from "next/link";

export default function ReturnRefundPage() {
  return <main className="min-h-dvh bg-[#f4f8fa] px-4 py-10 text-[#0a2540] sm:px-6 lg:py-16"><article className="mx-auto max-w-3xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-10"><Link className="text-sm font-bold text-[#0e7490] hover:underline" href="/">← Back to shop</Link><p className="mt-8 text-xs font-black tracking-[.24em] text-[#f97316] uppercase">Customer support</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Return &amp; Refund Policy – Marsa Edge Marine LLC</h1><PolicySection title="Returns"><p>You may request a return within 30 days of purchase.</p><p>To start a return, please email us at <a className="font-semibold text-[#0e7490] underline" href="mailto:sales@marsaedgemarine.com">sales@marsaedgemarine.com</a> or contact us by WhatsApp with your order details. We will provide return instructions and approval before you send the item back.</p><p>Returned items must be in original condition, unused, and in the original packaging with all accessories and documentation.</p><p>A 10% restocking fee will be deducted from your refund for approved returns.</p><p>Customers are responsible for all return shipping costs, customs duties, and related charges.</p><p>Items that are custom-ordered, non-stock, or made-to-order cannot be returned.</p></PolicySection><PolicySection title="Refunds"><p>Once the returned item is received and inspected, we will notify you by email.</p><p>If approved, your refund will be issued within 7–10 business days to the original payment method only.</p><p>If the product is returned damaged, incomplete, or not in resalable condition, a reasonable deduction will be made to cover repair, replacement, or repackaging costs.</p></PolicySection><PolicySection title="Cancellations"><p>Orders may be cancelled before shipment is processed without any penalty.</p><p>To cancel, please email <a className="font-semibold text-[#0e7490] underline" href="mailto:sales@marsaedgemarine.com">sales@marsaedgemarine.com</a> with your order number.</p><p>Once confirmed, refunds for cancellations will be processed within 48 hours.</p></PolicySection></article></main>;
}

function PolicySection({ children, title }: { children: React.ReactNode; title: string }) {
  return <section className="mt-9"><h2 className="text-xl font-black">{title}</h2><div className="mt-3 space-y-3 text-base leading-7 text-slate-600">{children}</div></section>;
}
