"use client";

import { useActionState, useState, type ReactElement, type ReactNode } from "react";
import type { Category } from "@/domain/catalog/category";
import type { CategoryField } from "@/domain/catalog/category-field";
import { createCategoryAction, deleteCategoryAction, updateCategoryAction } from "@/features/catalog/catalog.actions";
import { initialCreateCategoryActionState, type CreateCategoryActionState } from "@/features/catalog/catalog.types";

export function CategoryManager({ categories, fields }: { categories: Category[]; fields: CategoryField[] }): ReactElement { const [createOpen, setCreateOpen] = useState(false); const fieldsByCategory = new Map<number, CategoryField[]>(); for (const field of fields) fieldsByCategory.set(field.categoryId, [...(fieldsByCategory.get(field.categoryId) ?? []), field]); return <section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-[#102846]">All categories</h2><p className="mt-1 text-sm text-slate-500">{categories.length} categories, organised in the storefront taxonomy.</p></div><button className="min-h-11 rounded-xl bg-[#f05a28] px-4 text-sm font-bold text-white transition hover:bg-[#d94d20]" onClick={() => setCreateOpen(true)} type="button">Create category</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs tracking-wide text-slate-500 uppercase"><tr><th className="px-5 py-3">Category</th><th className="px-5 py-3">Parent</th><th className="px-5 py-3">Homepage</th><th className="px-5 py-3">Fields</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{categories.map((category) => <CategoryRow categories={categories} category={category} fields={fieldsByCategory.get(category.id) ?? []} key={category.id}/>)}</tbody></table></div>{createOpen ? <Modal close={() => setCreateOpen(false)} title="Create category"><CategoryForm categories={categories}/></Modal> : null}</section>; }

function CategoryRow({ categories, category, fields }: { categories: Category[]; category: Category; fields: CategoryField[] }): ReactElement { const [editOpen, setEditOpen] = useState(false); const [viewOpen, setViewOpen] = useState(false); const [state, action, pending] = useActionState<CreateCategoryActionState, FormData>(deleteCategoryAction, initialCreateCategoryActionState); const parent = categories.find((item) => item.id === category.parentCategoryId); return <><tr className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-800">{category.name}</p>{category.nameAr ? <p className="mt-1 text-xs text-slate-500" dir="rtl">{category.nameAr}</p> : null}</td><td className="px-5 py-4 text-slate-600">{parent?.name ?? "Main category"}</td><td className="px-5 py-4">{category.showOnHomepage ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">Visible</span> : <span className="text-slate-400">Hidden</span>}</td><td className="px-5 py-4 text-slate-600">{fields.length} field{fields.length === 1 ? "" : "s"}</td><td className="px-5 py-4"><div className="flex gap-2"><button aria-label={`View ${category.name}`} className="icon-button" onClick={() => setViewOpen(true)} type="button"><ViewIcon /></button><button aria-label={`Edit ${category.name}`} className="icon-button" onClick={() => setEditOpen(true)} type="button"><EditIcon /></button><form action={action} onSubmit={(event) => { if (!window.confirm(`Delete ${category.name}? It must have no products or child categories.`)) event.preventDefault(); }}><input name="id" type="hidden" value={category.id}/><button aria-label={`Delete ${category.name}`} className="icon-button border-rose-100 text-rose-700 hover:bg-rose-50" disabled={pending} type="submit"><DeleteIcon /></button></form></div>{state.message ? <p aria-live="polite" className="mt-2 text-xs text-rose-700">{state.message}</p> : null}</td></tr>{viewOpen ? <tr><td colSpan={5}><Modal close={() => setViewOpen(false)} title={category.name}><p className="text-sm text-slate-600">Parent: {parent?.name ?? "Main category"}</p><p className="mt-5 text-sm font-bold text-[#102846]">Custom fields</p><div className="mt-2 flex flex-wrap gap-2">{fields.length ? fields.map((field) => <span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700" key={field.id}>{field.label}</span>) : <span className="text-sm text-slate-500">No custom fields.</span>}</div></Modal></td></tr> : null}{editOpen ? <tr><td colSpan={5}><Modal close={() => setEditOpen(false)} title="Edit category"><CategoryForm categories={categories} category={category}/></Modal></td></tr> : null}</>; }

function CategoryForm({ categories, category }: { categories: Category[]; category?: Category }): ReactElement { const [state, action, pending] = useActionState<CreateCategoryActionState, FormData>(category ? updateCategoryAction : createCategoryAction, initialCreateCategoryActionState); const parentOptions = categories.filter((item) => item.id !== category?.id); return <form action={action} className="grid gap-5">{category ? <input name="id" type="hidden" value={category.id}/> : null}<div className="grid gap-5 sm:grid-cols-2"><Input defaultValue={category?.name} label="Category name" name="name" required/><Input defaultValue={category?.nameAr ?? ""} label="Category name (Arabic)" name="nameAr"/><label className="block text-sm font-semibold text-slate-700">Parent category<select className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 font-normal outline-none focus:border-[#0e568f]" defaultValue={category?.parentCategoryId ?? ""} name="parentCategoryId"><option value="">No parent category</option>{parentOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label className="block text-sm font-semibold text-slate-700">Category image {category ? "(replace optional)" : "*"}<input accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm" name="imageFile" required={!category} type="file"/></label>{!category ? <label className="block text-sm font-semibold text-slate-700">Custom fields<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-normal" name="customFields" placeholder={'Material\nVoltage\nCompatibility'}/></label> : null}<input name="homepageOrder" type="hidden" value={category?.homepageOrder ?? 0}/><div className="grid gap-3 sm:grid-cols-2"><label className="flex min-h-12 items-center gap-3 rounded-xl bg-slate-50 px-4 text-sm font-semibold"><input defaultChecked={category?.isFeatured} name="isFeatured" type="checkbox"/>Featured category</label><label className="flex min-h-12 items-center gap-3 rounded-xl bg-slate-50 px-4 text-sm font-semibold"><input defaultChecked={category?.showOnHomepage} name="showOnHomepage" type="checkbox"/>Show on homepage</label></div><Message state={state}/><button className="min-h-12 rounded-xl bg-[#f05a28] px-5 text-sm font-bold text-white disabled:bg-slate-300" disabled={pending} type="submit">{pending ? "Saving..." : category ? "Save changes" : "Create category"}</button></form>; }
function Input({ defaultValue, label, name, required, type = "text" }: { defaultValue?: number | string; label: string; name: string; required?: boolean; type?: "number" | "text" }): ReactElement { return <label className="block text-sm font-semibold text-slate-700">{label}<input className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-normal outline-none focus:border-[#0e568f]" defaultValue={defaultValue} min={type === "number" ? 0 : undefined} name={name} required={required} type={type}/></label>; }
function Modal({ children, close, title }: { children: ReactNode; close: () => void; title: string }): ReactElement { return <div aria-modal="true" className="fixed inset-0 z-50 flex items-end bg-slate-950/55 sm:items-center sm:justify-center sm:p-6" role="dialog"><section className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-white p-6 shadow-2xl sm:rounded-[2rem]"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black text-[#102846]">{title}</h2><button aria-label="Close modal" className="icon-button" onClick={close} type="button"><CloseIcon /></button></div>{children}</section></div>; }
function Message({ state }: { state: CreateCategoryActionState }): ReactElement | null { return state.message ? <p aria-live="polite" className={state.status === "success" ? "text-sm font-semibold text-emerald-700" : "text-sm font-semibold text-rose-700"}>{state.message}</p> : null; }
function ViewIcon(): ReactElement { return <svg aria-hidden="true" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg>; }
function EditIcon(): ReactElement { return <svg aria-hidden="true" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="m4 16.5-.5 4 4-.5L19 8.5 15.5 5 4 16.5Z"/><path d="m14.5 6 3.5 3.5"/></svg>; }
function DeleteIcon(): ReactElement { return <svg aria-hidden="true" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M4 7h16M10 11v6m4-6v6M9 7l1-3h4l1 3m-9 0 1 13h10l1-13"/></svg>; }
function CloseIcon(): ReactElement { return <svg aria-hidden="true" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>; }
